### PR TITLE
Use grayskull to update dependencies

### PR DESCRIPTION
**Pull request by jan-janssen**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
@conda-forge/core Can one of you merge this pull request? It is open for over a week without any reaction from the maintainers. In addition I am happy to join in maintaining this package to prevent this kind of issues in the future https://github.com/conda-forge/chex-feedstock/pull/23

**Comment by ocefpaf** [comment]
@jan-janssen consider adding yourself as a maintainer here.

**Comment by jan-janssen** [comment]
> @jan-janssen consider adding yourself as a maintainer here.

@ocefpaf Yes, I opened a pull request to add myself as maintainer in https://github.com/conda-forge/chex-feedstock/pull/23

**Pull request merged**
